//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicAppEntities : DbContext
    {
        public MedicAppEntities()
            : base("name=MedicAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgendarExamen> AgendarExamen { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<Examen> Examen { get; set; }
        public virtual DbSet<ExamenCategoria> ExamenCategoria { get; set; }
        public virtual DbSet<Medicamento> Medicamento { get; set; }
        public virtual DbSet<MedicamentoCategoria> MedicamentoCategoria { get; set; }
        public virtual DbSet<MedicamentoLaboratorio> MedicamentoLaboratorio { get; set; }
        public virtual DbSet<MedicamentoPresentacion> MedicamentoPresentacion { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Receta> Receta { get; set; }
    }
}
